name: Docker Image CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> "$GITHUB_ENV"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lonewolf1313/php-code:$IMAGE_TAG

      - name: Push the Docker image to Docker Hub
        run: docker push lonewolf1313/php-code:$IMAGE_TAG

      - name: Logout from Docker Hub
        if: always()
        run: docker logout
