name: Docker Image CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lonewolf1313/php-code:$(date +%s)

      - name: Push the Docker image to Docker Hub
        run: docker push lonewolf1313/php-code:$(date +%s)
